name: cortex_ai
description: "Cortex-AI — Detección de Parkinson mediante análisis de voz"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.2

  # Audio recording & playback
  record: ^6.2.1
  audioplayers: ^6.1.0

  # HTTP
  dio: ^5.7.0

  # Permissions
  permission_handler: ^11.3.1

  # Storage
  shared_preferences: ^2.3.3
  path_provider: ^2.1.4

  # Charts
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/Descripcion/1.png
    - assets/Descripcion/2.png
    - assets/Descripcion/3.png
    - assets/Descripcion/4.png
    - assets/Descripcion/5.png
